### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sesemaya** [sesemaya/discourse-material-theme#1]
Critical UI elements:
- [ ] Category box
- [ ] Date picker and tags
- [ ] Dialog popup (e.g. share a post, user profile popup, etc.)
- [ ] Reply box
- [ ] Modal (e.g. edit category, invite people to a post, etc.)
- [ ] User profile page layout

Nice to have:
- [ ] Convert all Fontawesome icons to Material Design icons
- [ ] Tidy up different views in user profile page
- [ ] Update all buttons accordingly (fab/flat/raised)
- [ ] Update all form controls accordingly

X (bonus):
- [ ] Tidy up admin page interface (currently only fixing issues that might cause all or part of the admin page nonfunctional)

**Comment by TurboProgramming** [comment]
Do you have any updates about:
- Material animations/transitions
- Converting Font Awesome icons to Material Design icons?
(@sesemaya)

**Comment by MeteorCoder** [comment]
> Do you have any updates about:

> - [ ] Material animation / transition

@ardacebi This can easily be implemented by using only CSS but the background of the line for textfields would have to totally depend on the primary color. It'd be great if you were able to finally improve upon your CSS skills, knowing that I now have skills with CSS, PHP, JS, SASS, some SCSS, and some Java.
